import TanstackProvider from '@/providers/TanstackProvider';
import '../styles/index.css';
import InitAuthProvider from '@/providers/InitAuthProvider';
import { GoogleOAuthProvider } from '@react-oauth/google';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <GoogleOAuthProvider
          clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}
        >
          <TanstackProvider>
            <InitAuthProvider>{children}</InitAuthProvider>
          </TanstackProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
